#!/usr/bin/env python3
"""Generate local frontend pages from the CLI's Markdown documentation."""

from __future__ import annotations

import argparse
import html
import json
import re
import sys
from pathlib import Path
from urllib.parse import urlsplit

import markdown

from webapp.documentation import (
    DOCUMENTATION_BY_SLUG,
    DOCUMENTATION_PAGES,
    OPERATOR_DOCUMENTATION_BY_SLUG,
    OPERATOR_DOCUMENTATION_PAGES,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_DIR = REPO_ROOT / "frontend" / "templates" / "docs"
#: Where the two operator documents land. A directory of its own, because
#: everything in `docs/` above is reachable from `/documentation` and
#: nothing in here is: these render only inside the authorised area.
OPERATOR_OUTPUT_DIR = REPO_ROOT / "frontend" / "templates" / "admin-docs"
PROJECT_URL = "https://github.com/sowoi/check-opencloud-security"
GENERATED_MARKER = "{# Generated by scripts/build_frontend_documentation.py. #}"
MARKDOWN_EXTENSIONS = ("fenced_code", "tables", "sane_lists", "toc", "attr_list")


def _section(source: str, start: str | None, end: str | None) -> str:
    """Select the configured heading range and drop a duplicate page title."""
    if start is not None:
        marker = f"{start}\n"
        if marker not in source:
            raise ValueError(f"start heading not found: {start}")
        source = marker + source.split(marker, 1)[1]
    if end is not None:
        marker = f"\n{end}\n"
        if marker not in source:
            raise ValueError(f"end heading not found: {end}")
        source = source.split(marker, 1)[0]

    # The frontend supplies the one h1. Full-document sources start with the
    # same title, while a selected README range keeps its first section and
    # demotes it below the page title later.
    if start is None:
        # Translated source files keep the English title followed by the translated
        # title so that the Markdown remains easy to compare with its source.
        # Neither belongs inside the article: the frontend renders the
        # localized page title in its header.
        source = re.sub(r"\A(?:# [^\n]+\n+)+", "", source, count=1)
    source = re.split(
        r"\n## (?:Trademarks and affiliation|Marken und Unabhängigkeit)\n",
        source,
        maxsplit=1,
    )[0]
    return source.rstrip() + "\n"


def _demote_headings(source: str) -> str:
    """Move README's top-level sections below the frontend's h1."""
    return re.sub(r"^(#{1,5})(?= )", r"#\1", source, flags=re.MULTILINE)


def _rewrite_relative_links(body: str, source_path: str) -> str:
    """Keep links between generated documents inside the frontend."""
    source_dir = Path(source_path).parent
    local = {
        str((REPO_ROOT / page.source).resolve()): page.slug
        for page in DOCUMENTATION_PAGES
    }
    for language in ("de", "fr"):
        local.update(
            {
                str((REPO_ROOT / "docs" / language / f"{page.slug}.md").resolve()): page.slug
                for page in DOCUMENTATION_PAGES
            }
        )

    def rewrite(match: re.Match[str]) -> str:
        raw = html.unescape(match.group(1))
        parts = urlsplit(raw)
        if parts.scheme or parts.netloc or not parts.path:
            return match.group(0)
        resolved = str((REPO_ROOT / source_dir / parts.path).resolve())
        if resolved in {
            str((REPO_ROOT / "docs" / "README.md").resolve()),
            str((REPO_ROOT / "docs" / "de" / "README.md").resolve()),
        }:
            target = "/documentation"
            if parts.fragment:
                target += f"#{parts.fragment}"
            return f'href="{html.escape(target, quote=True)}"'
        slug = local.get(resolved)
        if slug is not None:
            target = f"/documentation/{slug}"
        else:
            try:
                repository_path = Path(resolved).relative_to(REPO_ROOT)
            except ValueError:
                return match.group(0)
            target = f"{PROJECT_URL}/blob/main/{repository_path.as_posix()}"
        if parts.fragment:
            target += f"#{parts.fragment}"
        return f'href="{html.escape(target, quote=True)}"'

    return re.sub(r'href="([^"]+)"', rewrite, body)


#: Repository images the frontend serves itself, and the name each one takes
#: under ``/static/img``. The content security policy is ``img-src 'self'``,
#: so an image the frontend does not serve cannot be shown at all - a link to
#: the repository is the honest alternative, and that is what every image not
#: named here becomes.
#:
#: The line diagram is small and is the point of the section it sits in. The
#: interface screenshots are megabytes each and show the very page an operator
#: reading them is already looking at, which is not worth that in the bundle.
SERVED_IMAGES = {"img/architecture-three-layers.png": "architecture-three-layers.png"}
STATIC_IMAGE_DIR = REPO_ROOT / "frontend" / "static" / "img"
_IMAGE = re.compile(r'<img alt="([^"]*)" src="([^"]+)">')


def _rewrite_image_sources(body: str, source_path: str) -> str:
    """Serve the images the frontend carries, and link to the rest.

    Markdown written for the repository points at files beside it. A generated
    page is served from a different address, so a relative source resolves to
    a path that is not there - which is how these arrived as broken images.
    """
    source_dir = Path(source_path).parent

    def rewrite(match: re.Match[str]) -> str:
        alt, raw = match.group(1), html.unescape(match.group(2))
        parts = urlsplit(raw)
        if parts.scheme or parts.netloc or not parts.path:
            return match.group(0)
        try:
            repository_path = (
                (REPO_ROOT / source_dir / parts.path).resolve().relative_to(REPO_ROOT)
            )
        except ValueError:
            return match.group(0)
        served = SERVED_IMAGES.get(repository_path.as_posix())
        if served is not None:
            return f'<img alt="{alt}" src="/static/img/{served}" loading="lazy">'
        target = f"{PROJECT_URL}/blob/main/{repository_path.as_posix()}"
        return (
            f'<a href="{html.escape(target, quote=True)}" '
            f'rel="noopener noreferrer">{alt}</a>'
        )

    return _IMAGE.sub(rewrite, body)


def _escape_jinja(body: str) -> str:
    """Make examples such as GitHub expressions inert inside Jinja."""
    return (
        body.replace("{{", "&#123;&#123;")
        .replace("}}", "&#125;&#125;")
        .replace("{%", "&#123;%")
        .replace("%}", "%&#125;")
        .replace("{#", "&#123;#")
        .replace("#}", "#&#125;")
    )


# A page short enough to scan in one or two screens does not need a jump
# list; one long enough to have this many top-level sections does.
MIN_TOC_SECTIONS = 5


def _table_of_contents(body: str, language: str = "en") -> str:
    """A jump list of a page's own top-level sections, or "" below the threshold."""
    headings = re.findall(r'<h2 id="([^"]+)">(.*?)</h2>', body, flags=re.DOTALL)
    if len(headings) < MIN_TOC_SECTIONS:
        return ""
    links = "\n".join(
        f'  <a href="#{anchor}" lang="{language}">{text}</a>' for anchor, text in headings
    )
    return (
        '<nav class="docs-toc card section-gap" '
        "aria-label=\"{{ t('docs.guide.toc.aria') }}\" data-reveal>\n"
        "  <p class=\"kicker\">{{ t('docs.guide.toc.heading') }}</p>\n"
        f"{links}\n"
        "</nav>\n"
    )


def render_page(slug: str, language: str = "en") -> str:
    """Render one manifest entry as a complete Jinja template."""
    if language not in ("en", "de", "fr"):
        raise ValueError(f"unsupported guide language: {language}")
    page = DOCUMENTATION_BY_SLUG[slug]
    source_path = page.source if language == "en" else f"docs/{language}/{slug}.md"
    source = (REPO_ROOT / source_path).read_text(encoding="utf-8")
    selected = _section(
        source,
        page.start_heading if language == "en" else None,
        page.end_heading if language == "en" else None,
    )
    if page.demote_headings:
        selected = _demote_headings(selected)
    body = markdown.markdown(
        selected,
        extensions=list(MARKDOWN_EXTENSIONS),
        output_format="html5",
    )
    # Python-Markdown's table extension writes `style="text-align: ..."` on
    # every cell. The frontend CSP rejects inline style and the design system
    # already owns alignment, so generated prose must not carry it through.
    body = re.sub(r'\s+style="[^"]*"', "", body)
    body = _rewrite_relative_links(body, source_path)
    body = _rewrite_image_sources(body, source_path)
    body = _escape_jinja(body)
    toc = _table_of_contents(body, language)
    toc_block = f"{toc}\n" if toc else ""
    return f"""{GENERATED_MARKER}
{{% extends "base.html" %}}

{{% block title %}}{{{{ t('docs.{page.slug}.title') }}}}{{% endblock %}}
{{% block description %}}{{{{ t('docs.{page.slug}.description') }}}}{{% endblock %}}

{{% block content %}}
<section class="page-head">
  <p class="kicker">{{{{ t('docs.guide.kicker') }}}}</p>
  <h1>{{{{ t('docs.{page.slug}.title') }}}}</h1>
  <p class="lede">{{{{ t('docs.{page.slug}.description') }}}}</p>
</section>

{{% if locale not in ('en', 'de', 'fr') %}}
<p class="hint section-gap" lang="{{{{ locale }}}}">{{{{ t('docs.guide.english_notice') }}}}</p>
{{% endif %}}

{toc_block}<article class="docs-article card section-gap" data-reveal lang="{language}">
{body}
</article>

{{% include "_page-nav.html" %}}
{{% endblock %}}
"""


def render_operator_page(slug: str) -> str:
    """Render one operator document as a template the admin area includes.

    The same Markdown pipeline as :func:`render_page`, and a different wrapper:
    no catalogue keys for the title, because these two documents are the
    repository's own English and are not translated; no `_page-nav.html`,
    because that navigates the public guides; and the operator tab strip at
    the top, so the area reads as one place rather than three.

    The chrome around that strip is the area's, not the guides': `admin.css`
    is what styles the tabs, the signed-in band and the ruled heading, so a
    generated document loads it exactly as the hand-written tabs do. Without
    it the strip renders as bare links and the area stops looking like one
    place at the two tabs that are generated.
    """
    page = OPERATOR_DOCUMENTATION_BY_SLUG[slug]
    source = (REPO_ROOT / page.source).read_text(encoding="utf-8")
    selected = _section(source, page.start_heading, page.end_heading)
    body = markdown.markdown(
        selected,
        extensions=list(MARKDOWN_EXTENSIONS),
        output_format="html5",
    )
    body = re.sub(r'\s+style="[^"]*"', "", body)
    body = _rewrite_relative_links(body, page.source)
    body = _rewrite_image_sources(body, page.source)
    body = _escape_jinja(body)
    toc = _table_of_contents(body)
    toc_block = f"{toc}\n" if toc else ""
    return f"""{GENERATED_MARKER}
{{% extends "base.html" %}}

{{% block title %}}{page.title}{{% endblock %}}
{{% block description %}}{page.description}{{% endblock %}}

{{% block head %}}
<link rel="stylesheet" href="/static/css/admin.css">
{{% endblock %}}

{{% block content %}}
<section class="admin-band" role="note">
  <span class="admin-band-dot" aria-hidden="true"></span>
  <p class="flush">
    {{{{ t('admin.band', user=operator.username) }}}}
  </p>
  {{% if sign_out_url %}}
  <a class="admin-band-exit" href="{{{{ sign_out_url }}}}">{{{{ t('admin.band.signout') }}}}</a>
  {{% endif %}}
</section>

{{% include "_admin-tabs.html" %}}

<section class="page-head admin-head">
  <p class="kicker">{{{{ t('admin.docs.kicker') }}}}</p>
  <h1>{page.title}</h1>
  <p class="lede">{page.description}</p>
</section>

<p class="hint section-gap">{{{{ t.html('admin.docs.source', file=page_source) }}}}</p>

{toc_block}<article class="docs-article card section-gap" data-reveal lang="en">
{body}
</article>
{{% endblock %}}
"""


#: Where the operator area's configuration tab reads each variable's
#: documented default and description from. Generated rather than read at
#: runtime, because the web bundle does not ship `docs/`.
ENVIRONMENT_SOURCE = REPO_ROOT / "docs" / "webapp.md"
ENVIRONMENT_OUTPUT = REPO_ROOT / "webapp" / "environment_reference.py"
_ENVIRONMENT_ROW = re.compile(
    r"^\| `COS_WEB_(?P<name>[A-Z0-9_<>n]+)` \| (?P<default>.*?) \| (?P<description>.*) \|$"
)


def _plain(text: str) -> str:
    """One table cell as the plain text a template escapes and shows."""
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = text.replace("**", "").replace("`", "")
    text = re.sub(r"(?<!\w)\*([^*]+)\*(?!\w)", r"\1", text)
    return text.strip()


def render_environment_reference() -> str:
    """The `## Configuration` table of docs/webapp.md, as a Python mapping."""
    source = ENVIRONMENT_SOURCE.read_text(encoding="utf-8")
    section = _section(source, "## Configuration", "## How a scan flows through it")
    reference: dict[str, dict[str, str]] = {}
    for line in section.splitlines():
        match = _ENVIRONMENT_ROW.match(line.strip())
        if match is None:
            continue
        reference[match["name"]] = {
            "default": _plain(match["default"]),
            "description": _plain(match["description"]),
        }
    entries = "\n".join(
        f"    {json.dumps(name)}: {{\n"
        f"        \"default\": {json.dumps(values['default'], ensure_ascii=False)},\n"
        f"        \"description\": {json.dumps(values['description'], ensure_ascii=False)},\n"
        "    },"
        for name, values in reference.items()
    )
    return f'''"""
Generated by scripts/build_frontend_documentation.py from docs/webapp.md.

The documented default and description of every ``COS_WEB_*`` variable, for
the operator area's configuration tab. Edit the table in docs/webapp.md and
regenerate; CI fails when this file and the table disagree.
"""

REFERENCE: dict[str, dict[str, str]] = {{
{entries}
}}
'''


def generated_pages() -> dict[Path, str]:
    """Every generated path and the exact content it should carry."""
    return {
        ENVIRONMENT_OUTPUT: render_environment_reference(),
        **{
            OUTPUT_DIR / f"{page.slug}.html": render_page(page.slug)
            for page in DOCUMENTATION_PAGES
        },
        **{
            OUTPUT_DIR / "de" / f"{page.slug}.html": render_page(page.slug, "de")
            for page in DOCUMENTATION_PAGES
        },
        **{
            OUTPUT_DIR / "fr" / f"{page.slug}.html": render_page(page.slug, "fr")
            for page in DOCUMENTATION_PAGES
        },
        **{
            OPERATOR_OUTPUT_DIR / f"{page.slug}.html": render_operator_page(page.slug)
            for page in OPERATOR_DOCUMENTATION_PAGES
        },
    }


def served_images() -> dict[Path, Path]:
    """Each repository image the frontend serves, and where it is served from."""
    return {
        STATIC_IMAGE_DIR / name: REPO_ROOT / source
        for source, name in SERVED_IMAGES.items()
    }


def stale_images() -> list[Path]:
    """Static image copies that are missing or no longer match the repository."""
    return sorted(
        target
        for target, source in served_images().items()
        if not target.exists() or target.read_bytes() != source.read_bytes()
    )


def write_images() -> None:
    """Copy the served images the generated pages point at."""
    STATIC_IMAGE_DIR.mkdir(parents=True, exist_ok=True)
    for target, source in served_images().items():
        target.write_bytes(source.read_bytes())


def write_pages() -> None:
    """Write the manifest and remove generated pages no longer in it."""
    write_images()
    expected = generated_pages()
    for language in ("de", "fr"):
        (OUTPUT_DIR / language).mkdir(parents=True, exist_ok=True)
    OPERATOR_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for path in (*OUTPUT_DIR.rglob("*.html"), *OPERATOR_OUTPUT_DIR.rglob("*.html")):
        if path not in expected and path.read_text(encoding="utf-8").startswith(
            GENERATED_MARKER
        ):
            path.unlink()
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")


def stale_pages() -> list[Path]:
    """Return missing, stale or retired generated pages."""
    expected = generated_pages()
    stale = [
        path
        for path, content in expected.items()
        if not path.exists() or path.read_text(encoding="utf-8") != content
    ]
    for directory in (OUTPUT_DIR, OPERATOR_OUTPUT_DIR):
        if not directory.exists():
            continue
        stale.extend(
            path
            for path in directory.rglob("*.html")
            if path not in expected
            and path.read_text(encoding="utf-8").startswith(GENERATED_MARKER)
        )
    return sorted(set(stale))


def main() -> int:
    """Generate pages, or verify that the checked-in copies are current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a generated page differs instead of writing it",
    )
    args = parser.parse_args()
    if args.check:
        stale = stale_pages() + stale_images()
        if stale:
            for path in stale:
                print(path.relative_to(REPO_ROOT), file=sys.stderr)
            print(
                "Frontend documentation is stale; run "
                "python scripts/build_frontend_documentation.py",
                file=sys.stderr,
            )
            return 1
        return 0
    write_pages()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
