#!/usr/bin/env python3
"""Embed the Authentik blueprints into ``docker/setup-wizard.py``.

The wizard is documented as one file that needs no checkout - ``curl`` it and
run it - but the stack it generates mounts ``./authentik/blueprints``, and a
wizard that could only copy them from a checkout wrote an empty directory for
everybody who followed that documentation. Authentik then started with no
provider at all, and ``/admin`` answered 500.

So the wizard carries them. ``authentik/blueprints/*.yaml`` stays the one
place they are edited; this script rewrites the generated block between the
``embedded-blueprints`` markers in the wizard from those files::

    python scripts/embed_wizard_blueprints.py            # rewrite the block
    python scripts/embed_wizard_blueprints.py --check    # fail if it is stale

``tests/test_docker_wizard.py`` runs the check, so a blueprint edited without
re-running this fails the suite rather than shipping a wizard that writes the
old one.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WIZARD_PATH = REPO_ROOT / "docker" / "setup-wizard.py"
BLUEPRINT_DIRECTORY = REPO_ROOT / "authentik" / "blueprints"

# Every blueprint the wizard can write. Listed rather than globbed: a file
# dropped into the directory is not thereby something every deployment gets.
BLUEPRINT_NAMES = (
    "opencloud-scanner.yaml",
    "opencloud-admin.yaml",
    "opencloud-mfa.yaml",
    "opencloud-enrollment.yaml",
)

START_MARKER = "# --- embedded-blueprints:start ---"
END_MARKER = "# --- embedded-blueprints:end ---"
_BLOCK = re.compile(
    re.escape(START_MARKER) + r"\n.*?" + re.escape(END_MARKER), re.DOTALL
)


def _literal(text: str) -> str:
    """A triple-quoted literal that evaluates back to exactly ``text``."""
    escaped = text.replace("\\", "\\\\").replace('"""', '\\"\\"\\"')
    return '"""\\\n' + escaped + '"""'


def render_block() -> str:
    """The generated block, markers included."""
    lines = [
        START_MARKER,
        "# Generated by scripts/embed_wizard_blueprints.py from",
        "# authentik/blueprints/ - edit those files and re-run it, never this block.",
        "EMBEDDED_BLUEPRINTS: dict[str, str] = {",
    ]
    for name in BLUEPRINT_NAMES:
        content = (BLUEPRINT_DIRECTORY / name).read_text(encoding="utf-8")
        lines.append(f'    "{name}": {_literal(content)},')
    lines += ["}", END_MARKER]
    return "\n".join(lines)


def render_wizard(source: str) -> str:
    """The wizard's source with its block replaced by the current one."""
    if not _BLOCK.search(source):
        raise SystemExit(f"{WIZARD_PATH} has no {START_MARKER!r} block")
    block = render_block()
    return _BLOCK.sub(lambda _: block, source, count=1)


def is_current() -> bool:
    """Whether the wizard already embeds the blueprints as they are."""
    source = WIZARD_PATH.read_text(encoding="utf-8")
    return render_wizard(source) == source


def main() -> int:
    """Rewrite the block, or verify that it is current."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the embedded blueprints differ instead of writing them",
    )
    args = parser.parse_args()
    if args.check:
        if is_current():
            return 0
        print(
            "docker/setup-wizard.py embeds stale blueprints; run "
            "python scripts/embed_wizard_blueprints.py",
            file=sys.stderr,
        )
        return 1
    source = WIZARD_PATH.read_text(encoding="utf-8")
    WIZARD_PATH.write_text(render_wizard(source), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
