#!/usr/bin/env python3
"""
Record when each public page last really changed, for ``sitemap.xml``.

A ``<lastmod>`` taken from a template's modification time is a deployment
date: a checkout, a container build or an unpacked release tarball writes
every template at once, so every page would claim to have changed on release
day. This record keeps a date next to a digest of the template, and the date
moves only when the digest does - which is to say, only when the page really
changed.

``--check`` fails when a template no longer matches its record, the same way
the documentation and search-index checks do; run the script without it to
bring the record up to date and commit the result.
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import date, datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TEMPLATES = ROOT / "frontend" / "templates"

sys.path.insert(0, str(ROOT))
from webapp.revisions import REVISIONS_FILE, digest_of, load
from webapp.seo import PUBLIC_PAGES


def _today() -> str:
    return datetime.now(tz=timezone.utc).date().isoformat()


def current(known: dict[str, dict[str, str]], today: str) -> dict[str, dict[str, str]]:
    """
    The record this tree deserves: every public page, dates carried over.

    A page whose digest still matches keeps the date it had, which is the
    whole point; a new or edited page is dated today, the day the change is
    committed alongside this file.
    """
    pages: dict[str, dict[str, str]] = {}
    for page in PUBLIC_PAGES:
        template = TEMPLATES / page.template
        if not template.is_file():
            print(f"No template for {page.path}: {template}", file=sys.stderr)
            continue
        digest = digest_of(template)
        entry = known.get(page.template) or {}
        unchanged = entry.get("digest") == digest
        lastmod = str(entry.get("lastmod")) if unchanged else today
        try:
            date.fromisoformat(lastmod)
        except ValueError:
            lastmod = today
        pages[page.template] = {"digest": digest, "lastmod": lastmod}
    return pages


def render(pages: dict[str, dict[str, str]]) -> str:
    document = {
        "_comment": (
            "Generated by scripts/update_page_revisions.py - the sitemap's "
            "lastmod per public page. A date moves only when its template's "
            "digest does."
        ),
        "pages": pages,
    }
    return json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def stale(known: dict[str, dict[str, str]], pages: dict[str, dict[str, str]]) -> list[str]:
    """The templates whose recorded digest no longer describes them."""
    names = sorted(set(known) | set(pages))
    return [
        name
        for name in names
        if known.get(name, {}).get("digest") != pages.get(name, {}).get("digest")
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when a public page no longer matches its recorded revision",
    )
    arguments = parser.parse_args(argv)

    known = load(REVISIONS_FILE)
    pages = current(known, _today())
    outdated = stale(known, pages)
    if arguments.check:
        if outdated:
            for name in outdated:
                print(f"{name}", file=sys.stderr)
            print(
                "The sitemap revisions are stale; run "
                "python scripts/update_page_revisions.py",
                file=sys.stderr,
            )
            return 1
        return 0

    REVISIONS_FILE.parent.mkdir(parents=True, exist_ok=True)
    REVISIONS_FILE.write_text(render(pages), encoding="utf-8")
    if outdated:
        print(f"Recorded {len(outdated)} changed page(s): {', '.join(outdated)}")
    else:
        print(f"Page revisions unchanged: {len(pages)} public pages")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
