"""
Generated by scripts/build_frontend_documentation.py from docs/webapp.md.

The documented default and description of every ``COS_WEB_*`` variable, for
the operator area's configuration tab. Edit the table in docs/webapp.md and
regenerate; CI fails when this file and the table disagree.
"""

REFERENCE: dict[str, dict[str, str]] = {
    "REDIS_URL": {
        "default": "redis://127.0.0.1:6379/0",
        "description": "Where ephemeral state lives. memory:// runs without Redis, for a single-process evaluation. Include the password when Redis requires one: redis://:PASSWORD@redis:6379/0",
    },
    "RESULT_TTL": {
        "default": "3600",
        "description": "Seconds a scan stays readable. Also the TTL on every key",
    },
    "COMPARISON_TTL": {
        "default": "300",
        "description": "Seconds a comparison against an uploaded report stays readable. Clamped to 300; shorter is honoured",
    },
    "MAX_WORKERS": {
        "default": "5",
        "description": "Scans running at once",
    },
    "SCAN_CONCURRENCY": {
        "default": "4",
        "description": "Probes in flight within one scan",
    },
    "SCAN_TIMEOUT": {
        "default": "15",
        "description": "Seconds one HTTP probe may take",
    },
    "JOB_TIMEOUT": {
        "default": "180",
        "description": "Seconds a whole scan may take",
    },
    "VERIFY_TLS": {
        "default": "true",
        "description": "Verify the target's certificate. An untrusted chain becomes a finding either way",
    },
    "ALLOW_PRIVATE_TARGETS": {
        "default": "false",
        "description": "Allow private, loopback and link-local targets. On-premise deployments only",
    },
    "ALLOWED_HOSTS": {
        "default": "(empty)",
        "description": "Hostnames exempt from the SSRF guard, separated by ;",
    },
    "BLOCKED_TARGETS": {
        "default": "(empty)",
        "description": "Addresses this deployment will not scan, separated by ;. Hostnames, .suffix domains and CIDR ranges. Outranks both settings above; an entry that does not parse refuses startup",
    },
    "CHECK_DEBUG_PORTS": {
        "default": "false",
        "description": "Probe extra ports. Off in public: it is a port scan of somebody else's host",
    },
    "IPV6_ENABLED": {
        "default": "false",
        "description": "Whether this service has outbound IPv6 of its own. Off, IPv6 addresses are never dialled and the IPv4/IPv6 TLS comparison is skipped, so a missing route on the scanning host is not reported as a fault of the instance",
    },
    "IP_RATE_LIMIT": {
        "default": "10",
        "description": "Scans per client address per window. 0 disables",
    },
    "IP_RATE_WINDOW": {
        "default": "60",
        "description": "The window, in seconds",
    },
    "TARGET_COOLDOWN": {
        "default": "300",
        "description": "Seconds before the same instance may be scanned again. 0 disables",
    },
    "PROBE_LIMIT": {
        "default": "5",
        "description": "Scans from one client address that may find no OpenCloud within COS_WEB_PROBE_WINDOW before that address is blocked. The same host scanned again counts again. Set on the web service and the worker. 0 disables",
    },
    "PROBE_WINDOW": {
        "default": "300",
        "description": "The window those scans are counted in, in seconds",
    },
    "PROBE_BLOCK": {
        "default": "3600",
        "description": "How long the first block lasts, in seconds",
    },
    "PROBE_BLOCK_MAX": {
        "default": "86400",
        "description": "The longest a repeated block grows to; each block inside the repeat window lasts six times the one before",
    },
    "PROBE_REPEAT_WINDOW": {
        "default": "86400",
        "description": "How long after a block ends the next one escalates, in seconds. 0 never escalates",
    },
    "PROBE_IPV4_PREFIX": {
        "default": "24",
        "description": "The IPv4 network the probe block counts as one client. 32 counts single addresses",
    },
    "CLIENT_IPV6_PREFIX": {
        "default": "64",
        "description": "The IPv6 network every client limit counts as one client",
    },
    "DAILY_SCAN_LIMIT": {
        "default": "50",
        "description": "Scans per client per day, on top of the per-minute limit. 0 disables",
    },
    "DNS_CONSISTENCY_CHECK": {
        "default": "true",
        "description": "Resolve a submitted name twice and refuse it when the answers share no address",
    },
    "REQUIRE_APPROVAL": {
        "default": "false",
        "description": "Scan approved instances only; see Approval mode",
    },
    "APPROVED_TARGETS": {
        "default": "(empty)",
        "description": "Approved hostnames, .suffix domains, addresses and CIDR ranges, separated by ;. An entry that does not parse refuses startup",
    },
    "APPROVAL_DNS": {
        "default": "true",
        "description": "In approval mode, accept a _check-opencloud-security TXT record naming this service's hostname",
    },
    "MAX_BATCH_TARGETS": {
        "default": "10",
        "description": "Targets one POST /api/scans/batch may carry. Each still counts against every limit",
    },
    "TRUST_FORWARDED_FOR": {
        "default": "false",
        "description": "Read the client address from X-Forwarded-For",
    },
    "TRUSTED_PROXY_HOPS": {
        "default": "1",
        "description": "How many proxies of your own sit in front. The header is read from the right, this many entries in, because that end is the only part a proxy writes",
    },
    "RATE_LIMIT_SALT": {
        "default": "(random per process)",
        "description": "Salt for the rate-limit and cooldown keys. Required to be the same value in every web process of a deployment that runs more than one: without it each derives its own keys, and a client gets one allowance per process",
    },
    "PUBLIC_BASE_URL": {
        "default": "(required)",
        "description": "The stable origin this service is reached at, used for canonical links, sitemap.xml, and machine discovery. An unset value refuses startup so an incoming Host header cannot publish attacker-controlled URLs",
    },
    "INDEX_META_TAG": {
        "default": "(empty)",
        "description": "Up to 10 optional name=content metadata pairs on the landing page, separated by ;. Names and content are escaped separately; raw HTML, duplicate or reserved names, and prohibited platform metadata are refused",
    },
    "ALLOW_INDEXING": {
        "default": "true",
        "description": "Let search engines index the landing page and its explanation pages. Result pages are never indexable whatever this says",
    },
    "RELEASES_MODE": {
        "default": "off",
        "description": "Update check against the OpenCloud release feed: off, auto, feed, bundled",
    },
    "RELEASES_TOKEN": {
        "default": "(none)",
        "description": "GitHub token raising the feed's rate limit",
    },
    "SCHEDULE_REFRESH": {
        "default": "true",
        "description": "Re-read the OpenCloud release lifecycle page once a day and rate scans against what it says. One request a day for the whole deployment, not one per visitor",
    },
    "SCHEDULE_REFRESH_URL": {
        "default": "(the OpenCloud lifecycle page)",
        "description": "Where that schedule is read from. Operator configuration, so it may point at a mirror; never a request field",
    },
    "SCHEDULE_REFRESH_HOUR": {
        "default": "4",
        "description": "The hour (UTC) of the daily read. Worth varying between deployments so they do not all arrive at once",
    },
    "ADVISORY_REFRESH": {
        "default": "true",
        "description": "Ask the advisory feed once a day which vulnerabilities affect OpenCloud and rate scans against the answer. A refresh only ever adds an advisory, and never believes one with no version bounds",
    },
    "ADVISORY_REFRESH_URL": {
        "default": "https://api.osv.dev/v1/query",
        "description": "Where the advisories are read from. Operator configuration, so it may point at a mirror; never a request field",
    },
    "FRONTEND_DIR": {
        "default": "next to webapp/",
        "description": "Where templates and static assets live",
    },
    "ENABLE_DOCS": {
        "default": "false",
        "description": "Serve the browsable /docs and /redoc pages. The machine-readable documents are public whatever this says",
    },
    "ENABLE_MCP": {
        "default": "true",
        "description": "Serve the MCP endpoint at /mcp and register browser WebMCP tools. Ignored when the optional mcp extra is not installed",
    },
    "MCP_ALLOWED_HOSTS": {
        "default": "(empty)",
        "description": "Host values the MCP endpoint accepts, separated by ;. Empty turns the DNS-rebinding check off, which is right when a proxy already fixes the host",
    },
    "MCP_MAX_CONCURRENT_WAITS": {
        "default": "8",
        "description": "How many MCP tool calls may sit waiting for a scan at once. Reaching the ceiling refuses nothing: the scan is submitted and the uuid comes back to be polled",
    },
    "MCP_AUTH_ENABLED": {
        "default": "false",
        "description": "Require a bearer token on /mcp. Off, because the service is meant to answer anybody; a deployment that wants the opposite turns it on and names an issuer. See a sign-in on the MCP endpoint",
    },
    "MCP_AUTH_ISSUER": {
        "default": "(empty)",
        "description": "The OIDC issuer whose tokens are accepted, exactly as its discovery document spells it. A trailing slash is accepted either way",
    },
    "MCP_AUTH_AUDIENCE": {
        "default": "(empty)",
        "description": "What a token's aud claim must contain, normally the client ID agents authenticate as. Required when the sign-in is on: empty refuses to start, because a token minted for another application behind the same provider would otherwise open this one",
    },
    "MCP_AUTH_JWKS_URL": {
        "default": "(derived)",
        "description": "Where the signing keys are published. Defaults to <issuer>/jwks/, which is what a provider following the discovery specification answers with",
    },
    "MCP_AUTH_RESOURCE_URL": {
        "default": "(derived)",
        "description": "The URL this endpoint claims as its protected resource. Defaults to <COS_WEB_PUBLIC_BASE_URL>/mcp; a token's audience is checked against it",
    },
    "MCP_AUTH_SCOPES": {
        "default": "(empty)",
        "description": "Scopes a token must carry, separated by ;. Empty means any valid token from the issuer is enough",
    },
    "ADMIN_ENABLED": {
        "default": "false",
        "description": "Serve the operator's area at /admin. Off means the routes are not registered at all, so the path 404s like any other unknown one",
    },
    "ADMIN_PROXY_SECRET": {
        "default": "(unset)",
        "description": "The secret the authentik outpost adds as X-COS-Admin-Proxy, and the only reason the identity headers are believed. Required when the area is on, at least 32 characters, or startup refuses",
    },
    "ADMIN_USERS": {
        "default": "(empty)",
        "description": "Who may use the area, by authentik username, ;-separated. Empty with the area on refuses to start rather than meaning \"everybody\"",
    },
    "ADMIN_SIGN_OUT_URL": {
        "default": "(unset)",
        "description": "Where the area's sign-out link goes. This service holds no session to end, so the exit belongs to the provider in front - for the bundled stack, /outpost.goauthentik.io/sign_out. Unset, the band names the operator and offers no way out. Only a local path or an http(s) URL is accepted; anything else refuses to start, because the value is rendered as an href on a page whose content policy forbids script",
    },
    "ADMIN_AUDIT_BUFFER": {
        "default": "200",
        "description": "Recent audit records kept in memory for the live view, for a deployment that logs to stdout. 0 keeps none",
    },
    "ADMIN_REFRESH_COOLDOWN": {
        "default": "60",
        "description": "Shortest gap between two operator-triggered refreshes of the same reference data. The area's dry run - which reads both sources and applies nothing - is held back for the same interval under a key of its own, so it stays available in the moment after a refresh reported a failure",
    },
    "UPDATE_CHECK": {
        "default": "true",
        "description": "Ask PyPI whether a newer release of this service exists, for the operator's area only and at most every six hours. Set false with no outbound access",
    },
    "ADMIN_UPDATE_DIR": {
        "default": "(unset)",
        "description": "A directory shared with the updater service of docker-compose.dockerhub.yml. Set, the operator's area can install a newer release: it writes a request there and the updater pulls the image and recreates the web and worker containers, a short downtime. Unset, the area only says an update exists",
    },
    "AUDIT_LOG": {
        "default": "false",
        "description": "Write an audit record for every scan request, rejection and triggered limit",
    },
    "AUDIT_LOG_TARGETS": {
        "default": "false",
        "description": "Record the target hostname in the clear instead of as a fingerprint. On-premise deployments only",
    },
    "AUDIT_SALT": {
        "default": "(random per process)",
        "description": "Salt for the audit fingerprints. Setting one lets records correlate across a restart; rotating it ends that",
    },
    "AUDIT_LOG_FILE": {
        "default": "(the process output)",
        "description": "Write the audit records to this file instead, on a mount that outlives the container. Owner-readable only, and the ordinary log then carries no copy. A path that cannot be written refuses to start",
    },
    "AUDIT_LOG_MAX_BYTES": {
        "default": "10000000",
        "description": "Size at which that file is rotated. 0 never rotates",
    },
    "AUDIT_LOG_BACKUPS": {
        "default": "5",
        "description": "Rotated generations kept beside it. With the size above, the most the trail can occupy",
    },
    "AUDIT_LOG_ROTATION": {
        "default": "service",
        "description": "Who rotates that file: service (this process, by size) or external (logrotate on the host; this process only reopens the file it replaces). An unrecognised value refuses to start",
    },
    "PURGE_TOKEN": {
        "default": "(none)",
        "description": "Enables DELETE /api/purge and is the secret it requires. Unset means the endpoint answers 404 like any other path that is not there. At least 32 characters, or startup refuses: it is the whole authorisation for the one call that deletes other people's results. Five wrong answers from one address in five minutes are followed by 429",
    },
    "PURGE_SIGNING_KEY": {
        "default": "(none)",
        "description": "Signs the proof of deletion. Unset still erases, but the receipt cannot be verified afterwards",
    },
    "EXPORT_SIGNING_KEY": {
        "default": "(none)",
        "description": "Adds an X-COS-Signature HMAC-SHA256 header to every JSON, CSV, SARIF and PDF export",
    },
    "ENCRYPT_RESULTS": {
        "default": "false",
        "description": "Encrypt the stored result document with AES-256-GCM. Requires a key; a process asked to encrypt without one refuses to start",
    },
    "WEBHOOK_SECRET": {
        "default": "(none)",
        "description": "Read at startup but not used by the web service, which sends no webhooks; signed webhooks are the plugin's --webhook-secret. Listed so that setting it is not mistaken for a typo",
    },
    "ENCRYPTION_KEY_<n>": {
        "default": "(none)",
        "description": "A 32-byte key as 64 hex characters. The highest <n> encrypts, lower ones still decrypt, which is how a key is rotated",
    },
}
